### ISSUE TITLE
'Could not find command "cldr:download"'

### ISSUE THREAD

**Issue by smostovoy** [ruby-i18n/ruby-cldr#24]
Trying to run 'thor cldr:download' after "bundle install" but I'm geting this error.
Ruby 2.1
Rails 4.0

**Comment by camertron** [comment]
I think this was fixed a long time ago. If you're still experiencing this issue please file another one with steps to reproduce and we'll take a look :)

**Comment by tp-beesolver** [comment]
I landed into this issue couple of times and everytime i found out that i've given .rb extension instead of .thor :)
