### ISSUE TITLE
Collaborate with Twitter CDLR gem

### ISSUE THREAD

**Issue by sandstrom** [ruby-i18n/ruby-cldr#258]
Awesome gem! 💎 

This gem has slightly overlapping scope with this one:

https://github.com/twitter/twitter-cldr-rb

Maybe there is room for collaboration?

For example, perhaps the logic of extracting data from CLDR data sets could be shared between this gem and the aforementioned one (presumably by having that gem depend on this one, perhaps by moving some of the extraction logic from Twitter-CDLR to this one).

It could be other things too! Mostly wanted to raise the idea.

cc @camertron

**Comment by camertron** [comment]
Hey @sandstrom, thanks for bringing this up! As it happens, twitter-cldr-rb [already uses ruby-cldr](https://github.com/twitter/twitter-cldr-rb/blob/d57e652ab7308539841a9477cd18965dc32d7cf5/Gemfile#L23) to grab data for a number of its features. I have however been slowly migrating twitter-cldr-rb away from ruby-cldr for a number of reasons, with the goal of eventually dropping it as a dependency entirely. A collaboration is possible, but I'm not sure I would have the time or inclination to work on it 😦

**Comment by sandstrom** [comment]
@camertron Alright, I understand!

I don't know either of these projects well enough to have any insights or suggestions. Just wanted to raise the question, to see if there was an opportunity to share the CLDR extraction layer.

twitter-cldr is a great gem, I've used it a lot! 💎 

It just seems like a project that has wide usage and might benefit from being "less tied to Twitter" (nothing against Twitter here though, just that company priorities may shift over time). And sharing the data extraction could have been one step in that direction.

Either way, don't feel any pressure here, just wanted to raise it 😄
