### ISSUE TITLE
Support for CLDR v25?

### ISSUE THREAD

**Issue by erikogan** [ruby-i18n/ruby-cldr#30]
Thank you for the work you have done so far!

We are looking at using this library (specifically for plurals first), and noticed that v25 was released ~2 weeks ago. It adds a whole new dimension to pluralization (ordinals, cardinals, and ranges, oh my!) as well as much finer grained cases for MANY languages (largely around decimals/fractions).

I was toying with the idea of trying to update this library to start using v25 rules, and I was hoping I wasn’t the only one working on it, so we could share the load.

**Comment by drewish** [comment]
In case it makes it easier to stay current, I noticed that the 32 is available in a JSON format from a GitHub repo: https://github.com/unicode-cldr/cldr-json

**Comment by Korri** [comment]
We are now on CLDR 34
