### ISSUE TITLE
Clarify ruby version requirement

### ISSUE THREAD

**Issue by Korri** [ruby-i18n/ruby-cldr#50]
Right now the Readme says `Ruby 1.9 (if you want well-ordered Hashes to be exported)`

But we only run CI on ruby 2.3

**Comment by camertron** [comment]
I'd be in favor of officially dropping 1.9 support and only supporting supported rubies. I think that means 2.4, 2.5, and 2.6.

**Comment by movermeyer** [comment]
Agreed. 

Defining a minimum version would also mean that we could clean up some old stuff. For example, we could generate hashes using Ruby 1.9+ syntax, instead of: https://github.com/ruby-i18n/ruby-cldr/blob/def445f039952fa383b58df6bb702541b5846bbd/lib/cldr/export/data/plurals/rules.rb#L33
