### ISSUE TITLE
Change default branch name to `main`

### ISSUE THREAD

**Issue by movermeyer** [ruby-i18n/ruby-cldr#97]
The Git ecosystem is moving away from the default branch name of `master`, towards the name `main`.

e.g. All new repos on GitHub/GitLab/Bitbucket now use `main` as the default branch name for new repositories.

Change the default branch of `ruby-cldr` to use `main`.

### How is this done?

1. [Rename the default branch in the GitHub UI](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/changing-the-default-branch) (Requires Administrator rights on the repo)
2. Use `git grep master` and update mentions of the outdated branch name in documentation and URLs.

Developers with local clones will have to perform a one-time update of the local clones by running:

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```

These commands are also shown to developers who visit the repo in the GitHub interface, so it doesn't require additional advertising work from our end.

**Comment by movermeyer** [comment]
This change requires someone with the [`Admin` role](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization) on the repo.

**Comment by svenfuchs** [comment]
Sure thing, just changed it.

But wait, you need admin status for something like this? Are there any other relevant things the maintainer status isn't enough for? I suppose maybe adding others as collaborators might be. I will change you to admin just in case ...
